CREATE TABLE IF NOT EXISTS sensor_readings (
  id              SERIAL PRIMARY KEY,
  received_at     TIMESTAMPTZ DEFAULT NOW(),
  timestamp       BIGINT NOT NULL,
  temperature_c   FLOAT,
  pressure_hpa    FLOAT,
  humidity_pct    FLOAT,
  gas_kohms       FLOAT,
  altitude_m      FLOAT,
  pm10_env        INTEGER,
  pm25_env        INTEGER,
  pm100_env       INTEGER,
  particles_03um  INTEGER,
  particles_05um  INTEGER,
  particles_10um  INTEGER,
  particles_25um  INTEGER,
  particles_50um  INTEGER,
  particles_100um INTEGER,
  f1_415nm        FLOAT,
  f2_445nm        FLOAT,
  f3_480nm        FLOAT,
  f4_515nm        FLOAT,
  f5_555nm        FLOAT,
  f6_590nm        FLOAT,
  f7_630nm        FLOAT,
  f8_680nm        FLOAT,
  clear           FLOAT,
  nir             FLOAT,
  flicker_hz      INTEGER,

  -- Microphones
  mic_loud_digital  INTEGER,
  mic_loud_analog   INTEGER,
  mic_low_digital   INTEGER,
  mic_low_analog    INTEGER
);